version: "2.3"
services:

  postgres:
    image: postgres:12.0
    mem_limit: 200M
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data